#include "position/DtwMatcher.h"
#include <algorithm>
#include <cmath>
namespace temposcore {
float DtwMatcher::frameDistance(const AudioFeatureFrame&a,const ScoreFeatureFrame&b)noexcept{if(!a.valid)return 1e6f;float aa=0,bb=0,d=0;for(int i=0;i<12;++i){aa+=a.chroma[i]*a.chroma[i];bb+=b.chroma[i]*b.chroma[i];d+=a.chroma[i]*b.chroma[i];}float cosine=(aa>0&&bb>0)?d/std::sqrt(aa*bb):0;constexpr float LiveOnsetScale=100.0f;return .75f*(1-cosine)+.25f*std::abs(std::min(1.0f,a.onset/LiveOnsetScale)-b.onset);}
PositionObservation DtwMatcher::global(const FeatureRing&l)noexcept{return search(l,0,true);} PositionObservation DtwMatcher::local(const FeatureRing&l,double p)noexcept{return search(l,p,false);}
PositionObservation DtwMatcher::search(const FeatureRing&l,double predicted,bool localSearch)noexcept{const size_t n=l.copy(live_);PositionObservation o;o.globalMatch=localSearch;if(!n)return o;const auto&ref=reference_.frames();size_t best=0;float bestCost=1e30f,second=1e30f;size_t valid=0;for(size_t i=0;i<n;++i)if(live_[i].valid)++valid;if(valid<n/2||ref.empty())return o;for(size_t s=0;s<ref.size();++s){if(localSearch&&std::abs(ref[s].nominalSeconds-predicted)>300)continue;if(ref.size()-s<=((n-1)*65/100))continue;dp_[0]=frameDistance(live_[0],ref[s]);for(size_t i=1;i<n;++i){const size_t lo=i*65/100,hi=std::min({i*150/100,ref.size()-s-1,MaxBand-1});const size_t loPrev=(i-1)*65/100,hiPrev=std::min({(i-1)*150/100,ref.size()-s-1,MaxBand-1});std::fill(dp_.begin()+i*MaxBand+lo,dp_.begin()+i*MaxBand+hi+1,1e30f);for(size_t k=lo;k<=hi;++k){float prev=1e30f;if(k<=hiPrev)prev=std::min(prev,dp_[(i-1)*MaxBand+k]);if(k>0&&k-1>=loPrev&&k-1<=hiPrev)prev=std::min(prev,dp_[(i-1)*MaxBand+k-1]);if(k>lo)prev=std::min(prev,dp_[i*MaxBand+k-1]);if(prev<1e30f)dp_[i*MaxBand+k]=prev+frameDistance(live_[i],ref[s+k]);}}const size_t lo=(n-1)*65/100,hi=std::min({(n-1)*150/100,ref.size()-s-1,MaxBand-1});float cost=1e30f;size_t end=lo;for(size_t k=lo;k<=hi;++k)if(dp_[(n-1)*MaxBand+k]<cost){cost=dp_[(n-1)*MaxBand+k];end=k;}if(cost>=1e30f)continue;cost/=static_cast<float>(n+end);if(cost<bestCost){second=bestCost;bestCost=cost;best=s;}else if(cost<second)second=cost;}
if(bestCost>=1e30f)return o;o.quarterBeatPosition=ref[best].quarterBeatPosition;o.matchQuality=1/(1+bestCost);o.ambiguityMargin=std::max(0.0f,second-bestCost);o.confidence=o.matchQuality*std::min(1.0f,static_cast<float>(n)/60.0f)*std::min(1.0f,o.ambiguityMargin*10);o.valid=o.confidence>=.5f;return o;}
}
